### ISSUE TITLE
Code using the library compiles with warnings for Elixir v1.18.4 while outright breaking in v1.19.5

### ISSUE THREAD

**Issue by DaTrader** [OvermindDL1/protocol_ex#68]
@OvermindDL1 

In Elixir 1.18.4 the warnings are of type:

```
given types:

        dynamic({term(), term()})

but expected one of:

        dynamic(:__@@NO_MATCH@@__)
```

In Elixir 1.19.5 it breaks the compilation with something like the following:

```
== Compilation error in file lib/my_app/foo_caching.ex ==
** (ProtocolEx.MissingRequiredProtocolDefinition) On Protocol `Elixir.MyAppCache.Relatable` missing a required protocol callback on `Relatable.Foo.Update` of:  extract_invalidators/1
    (protocol_ex 0.5.0) lib/protocol_ex.ex:692: anonymous fn/3 in ProtocolEx.verify_valid_spec_on_module/3
    (elixir 1.19.5) lib/enum.ex:1688: Enum."-map/2-lists^map/1-1-"/2
    (protocol_ex 0.5.0) lib/protocol_ex.ex:678: ProtocolEx.verify_valid_spec_on_module/3
    lib/my_app/cache/foo_caching.ex:23: (file)
```

**Comment by DaTrader** [comment]
@josevalim Should I also report it an Elixir issue or do you think it's just the library that should take care of the compatibility (breaking changes) like this one?

**Comment by josevalim** [comment]
I will see if I can spot something quickly. If I cannot, then I will ask for a way to isolate it. ~But the function name hints it may be relying on private APIs~. :)

EDIT: I was wrong. The code is fine and no private APIs being used as far as I can see. Sorry for the misleading comment @OvermindDL1.

**Comment by josevalim** [comment]
@DaTrader please provide a minimum reproducer, because I cannot reproduce the issue at hand.

**Comment by DaTrader** [comment]
Will do

**Comment by josevalim** [comment]
Oh, the bug may be related to assuming modules are loaded after compiling. Try adding `Code.ensure_loaded!(module)` before the library calls `verify_valid_spec_on_module`.

**Comment by OvermindDL1** [comment]
Honestly, I'm using this project heavily in some work projects, but we are still on an old Elixir version as trying to upgrade 'everything' had too many breaking changes and not enough time to work on it...  ^.^;

I will happily accept PR's, or if a maintainer wants to step up for modern Elixir versions.  :-)

(I still think this functionality in 'some' form should be in normal protocols in Elixir itself, that would be amazing!)

> Oh, the bug may be related to assuming modules are loaded after compiling. Try adding Code.ensure_loaded!(module) before the library calls verify_valid_spec_on_module.

Is this not the case in modern versions?  Or has my usage of it just not hit this issue since I load them quickly?

**Comment by josevalim** [comment]
It changed either in Elixir v1.18 or v1.19, but something may have made it work by accident. Generally speaking, it is always safer to do a `Code.ensure_loaded?(...)` before `function_exported` checks, unless you are certain it has been loaded.

**Comment by DaTrader** [comment]
@josevalim Here's what happens in the real app with `Code.ensure_loaded!` added:

The code inspecting the returned values in the library:

```
    IO.inspect( impl_name, label: "impl_name")

    Module.create(impl_name, impl_quoted, caller_env) # Macro.Env.location(caller_env))
    |> IO.inspect( label: "Module.create")

    Code.ensure_loaded!(impl_name)
    |> IO.inspect( label: "Code.ensure_loaded!")

    verify_valid_spec_on_module(name, spec, impl_name)
```

Elixir 1.18.4 console output:

1. 12 module names (out of n in total)
2. 2 `Module.create` results out of the 12 above
3. 2 `Code.ensure_loaded!` results 
..
[`impl_name`, `Module.create` and `Code.ensure_leaded!` interleaved until every single one of n in total is processed]

Elixir 1.19.5 console output:

1. 12 module names
2. 11 out of the 12 `Module.create` results 
3. `Code.ensure_loaded!` crashes with:

```
== Compilation error in file lib/my_app/cache/foo_caching.ex ==
** (ArgumentError) could not load module MyApp.Cache.CacheableResource.Foo.Resource due to reason :nofile
    (elixir 1.19.5) lib/code.ex:2018: Code.ensure_loaded!/1
    (protocol_ex 0.6.0) lib/protocol_ex.ex:273: ProtocolEx.defimplEx_do/6
    lib/my_app/cache/foo_caching.ex:5: (file)
```

The module for which `Code.ensure_loaded!` crashes with `:nofile` is the first out of 11 modules returned by `Module.create`, so it's not like it wasn't created.

**Comment by DaTrader** [comment]
@josevalim Do you still need a minimum reproducer or the above output is enough to give you a clue on what may be the problem?

**Comment by DaTrader** [comment]
Interesting enough, not even inserting `Process.sleep/1` before `Code.ensure_loaded!` can help. It only permits more of the `impl_name` inspects and more of the `Module.create` calls, but eventually it all fails at first `Code.ensure_loaded!`

**Comment by DaTrader** [comment]
@josevalim Grok helped me find a fix. The app now compiles and works, but am not sure if this is the correct way.

"The issue stems from a major deliberate change in Elixir 1.19 (lazy module loading), introduced to eliminate code-server bottlenecks and significantly speed up compilation (often 2–4× in large projects).
What Changed in 1.19

Before 1.19 (e.g., 1.18.4): Modules created via Module.create/3 (or defmodule) were automatically loaded into the runtime immediately after compilation. This happened via :code.load_binary(Module, BeamLocation, Binary) inside :elixir_module.compile (the Erlang-side compiler primitive that Module.create/3 delegates to). The load was eager, so the module was immediately available in memory (no .beam file required for dynamically created modules). Code.ensure_loaded!/1 (and :code.ensure_loaded/1) succeeded right away.
In 1.19+: Modules are no longer automatically loaded after compilation/creation ("lazy loading"). The compiler (and :elixir_module.compile) now controls loading more strictly for determinism, parallelism during compilation, and reduced pressure on the single-process Erlang code server. The default autoload flag is now false (controlled via compile options or internal flags like Forceload/autoload in compile opts). Module.create/3 still compiles successfully and returns {:module, module, binary, last_result}, but it does not call :code.load_binary/3. The module exists only as bytecode in memory (or potentially written to .beam only if invoked during source-file compilation)."

It suggests the following change:

```
    if Code.ensure_loaded?(impl_name) do
      :code.purge(impl_name)
    end

    { :module, ^impl_name, binary, _} = Module.create(impl_name, impl_quoted, caller_env)
    :code.load_binary( impl_name, ~c"", binary)  # filename "" is conventional for in-memory
    Code.ensure_loaded!(impl_name)

    verify_valid_spec_on_module(name, spec, impl_name)
```

**Comment by josevalim** [comment]
>    :code.load_binary( impl_name, ~c"", binary)  # filename "" is conventional for in-memory

Yes, this is correct. Note you don't nee the ensure_loaded call right after.

**Comment by DaTrader** [comment]
@josevalim Thanks,  Now what can we do about the warnings from using the library (present in both 1.18.4 and 1.19.5):

```
     warning: incompatible types given to JsonDecodable.decode/1:

         JsonDecodable.decode({for, data})

     given types:

         dynamic({term(), %{...}})

     but expected one of:

         dynamic(:__@@NO_MATCH@@__)

     where "data" was given the type:

         # type: dynamic(%{...})
         # from: lib/jsoned/decoder.ex:196:30
         %{} = data

     where "for" was given the type:

         # type: dynamic()
         # from: lib/jsoned/decoder.ex:196:21
         for

     typing violation found at:
     │
 197 │     JsonDecodable.decode( { for, data})
     │                   ~
     │
```

**Comment by DaTrader** [comment]
@OvermindDL1 As you can see above (https://github.com/OvermindDL1/protocol_ex/issues/68#issuecomment-3789762443) the app using the lib now compiles (and runs) in Elixir v1.19.5 with that patch. 

However, there's another issue when you run "mix test" with both Elixir 1.18.4 and 1.19.5:

```
** (ArgumentError) tried to unquote invalid AST: [{Blah.Integer, [1], [Blah]}, {Blah.TaggedTuple.Vwoop, 0, [Blah]}, {Blah.MineOlStruct, 0, [Blah]}]
Did you forget to escape term using Macro.escape/1?
    (elixir 1.18.4) src/elixir_quote.erl:554: :elixir_quote.argument_error/1
    (protocol_ex 0.6.0) lib/protocol_ex.ex:469: ProtocolEx."MACRO-resolveProtocolEx"/4
    (protocol_ex 0.6.0) expanding macro: ProtocolEx.resolveProtocolEx/2
    test/test_helper.exs:76: Resolver (module)
```

I tried to debug this using LLMs but although they identify the problem (stricter rules for Macros since Elixir 1.16), they get stuck trying to fix it.

It also seems, but I am not absolutely sure about it, that beyond the macro bug above, the `consolidate/2` will also need similar patching to the one in `defimplEx_do/6`.

This will most likely require your intervention for I can't just create a PR that only works for me because in my app I'm not using the `ProtocolEx.resolveProtocolEx/2` macro.

Please let me know what you plan to do with it, for if you can't find time to attend to the issue anytime soon (because of the reasons you explained earlier), then I'll simply have to fork the unofficial 0.5.0 commit (the one you made back then when it started to fail with new LV umbrella apps) and apply the patch to me fork.

**Comment by OvermindDL1** [comment]
```ex
** (ArgumentError) tried to unquote invalid AST: [{Blah.Integer, [1], [Blah]}, {Blah.TaggedTuple.Vwoop, 0, [Blah]}, {Blah.MineOlStruct, 0, [Blah]}]
```
Yeah I'm guessing the AST format changed a bit...  All of these were generated by quoting actual code examples in the past, so I'm guessing that the AST format has changed recently, interesting...

**Comment by OvermindDL1** [comment]
Probably an easy fix though from some quick testing on my phone, will try when I get back to a computer.

**Comment by OvermindDL1** [comment]
Yeah I fixed it remote from my phone, 'that' error is fixed, it was indeed a 2 character change, lol.  I'll do the rest of what you put above when I get to a computer.  :-)

**Comment by OvermindDL1** [comment]
I think I got everything, I pushed it to github, can you test the version here and see if it works, if not give me more errors (and maybe a minimal testcase to add so I can test it locally)?  If it's good then I'll publish it as 0.5.1 and hope the minimal elixir version doesn't need to be bumped from 1.15?

**Comment by OvermindDL1** [comment]
I just tested on elixir 1.15 as well and they still pass, so 1.15 should still be a good minimum.

**Comment by DaTrader** [comment]
@OvermindDL1 It all compiles and works now both in 1.18.4 and 1.19.5. Thank you so much for the effort!

**Comment by OvermindDL1** [comment]
Awesome!  And published to:  https://hex.pm/packages/protocol_ex/0.5.1

**Comment by DaTrader** [comment]
@OvermindDL1 One thing still left out there is those warnings regarding the default protocol implementations. Please check the issue I reported for Elixir and the subsequent convo with Jose: 

https://github.com/elixir-lang/elixir/issues/15079

I've tried his suggestion and it works, but it litters the default implementation code. Would you consider putting this Elixir type system work around in the library itself, so that regardless of whether you raise because there's no default implementation or you invoke the one provided by the user, you always do it by first fooling the type system with the `Process.get/1` call?
